config/routes.rb
Hacker::Application.routes.draw do
  devise_for :users

  resources :programmers
  root :to => redirect("/programmers")
namespace :admin do  
      resources :users, only: :show do
         post :generate_new_password_email
      end
   end

end

app/models/model.rb
class Model < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/programmer.rb
class Programmer < ActiveRecord::Base
	geocoded_by :City
	after_validation :geocode
	acts_as_gmappable :process_geocoding => false
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/programmers_controller.rb
class ProgrammersController < ApplicationController
  
  # GET /programmers
  # GET /programmers.json
   def generate_new_password_email
      user = User.find(params[:user_id])
      user.send_reset_password_instructions
      flash[:notice] = "Reset password instructions have been sent to #{user.email}."
      redirect_to admin_user_path(user)
   end
  def index
    @programmers = Programmer.all
    @pins = @programmers.to_gmaps4rails
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @programmers }
    end
  end

  # GET /programmers/1
  # GET /programmers/1.json
  def show
    @programmer = Programmer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @programmer }
    end
  end

  # GET /programmers/new
  # GET /programmers/new.json
  def new
    @programmer = Programmer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @programmer }
    end
  end

  # GET /programmers/1/edit
  def edit
    @programmer = Programmer.find(params[:id])
  end

  # POST /programmers
  # POST /programmers.json
  def create
    @programmer = Programmer.new(params[:programmer])

    respond_to do |format|
      if @programmer.save
        format.html { redirect_to @programmer, notice: 'Programmer was successfully created.' }
        format.json { render json: @programmer, status: :created, location: @programmer }
      else
        format.html { render action: "new" }
        format.json { render json: @programmer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /programmers/1
  # PUT /programmers/1.json
  def update
    @programmer = Programmer.find(params[:id])

    respond_to do |format|
      if @programmer.update_attributes(params[:programmer])
        format.html { redirect_to @programmer, notice: 'Programmer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @programmer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /programmers/1
  # DELETE /programmers/1.json
  def destroy
    @programmer = Programmer.find(params[:id])
    @programmer.destroy

    respond_to do |format|
      format.html { redirect_to programmers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/programmers_helper.rb
module ProgrammersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<style>
	#user_nav
	{color:blue;

	}
	</style>
  <title>Hacker</title>
  <link rel="stylesheet" href="http://railsgirls.com/assets/bootstrap.css">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<h3>
<div class="container"><%= yield %></div>
<div id="user_nav">
  <% if user_signed_in? %>
    Signed in as <%= current_user.email %>. Not you?
    <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
  <% end %>
</div>
</h3>
<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container"><a class="brand" href="/">Meet and Hack!</a><ul class="nav">
              <li class="active"><a href="/programmers">Hackers</a></li>
			

            </ul>
        </div>
    </div>
</div>
<footer>
    <div class="container">Host a hackthaon 2013</div>
</footer>
</body>
</html>

app/views/programmers/_form.html.erb
<%= form_for(@programmer) do |f| %>
  <% if @programmer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@programmer.errors.count, "error") %> prohibited this programmer from being saved:</h2>

      <ul>
      <% @programmer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Hacker_name %><br />
    <%= f.text_field :Hacker_name %>
  </div>
  <div class="field">
    <%= f.label :Skillset %><br />
    <%= f.text_field :Skillset %>
  </div>
  <div class="field">
    <%= f.label :City %><br />
    <%= f.text_field :City %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/programmers/edit.html.erb
<h1>Editing programmer</h1>

<%= render 'form' %>

<%= link_to 'Show', @programmer %> |
<%= link_to 'Back', programmers_path %>

app/views/programmers/index.html.erb
<h3> 
<%= link_to 'New hacker?', new_programmer_path %>
</h3>
<br>
<table>
 
  <tr>
    <th>Hacker name</th>
    <th>Skillset</th>
    <th>City</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @programmers.each do |programmer| %>
  <tr>
    <td><%= programmer.Hacker_name %></td>
    <td> <%= programmer.Skillset %> </td>
    <td> <%= programmer.City %> </td>
    <td> <%= programmer.email %> </td>
    <td> <%= link_to 'Show', programmer %> </td>
    <td> <%= link_to 'Edit', edit_programmer_path(programmer) %> </td>
    <td> <%= link_to 'Destroy', programmer, confirm: 'Are you sure?', method: :delete %> </td>
  </tr>
<% end %>
</table>
<br/> 
<%= gmaps4rails(@pins) %> 
<%= yield :scripts %>

<br />

app/views/programmers/new.html.erb
<h1>New programmer</h1>

<%= render 'form' %>

<%= link_to 'Back', programmers_path %>

app/views/programmers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Hacker name:</b>
  <%= @programmer.Hacker_name %>
</p>

<p>
  <b>Skillset:</b>
  <%= @programmer.Skillset %>
</p>

<p>
  <b>City:</b>
  <%= @programmer.City %>
</p>

<p>
  <b>Email:</b>
  <%= @programmer.email %>
</p>
 <%=form_tag(admin_user_generate_new_password_email_path(@user)) do %>
      <%=submit_tag 'Send Reset Password Email', class: 'button', :confirm => 'Are you sure you want to mail reset password instructions?' %>
   <% end %>

<%= link_to 'Edit', edit_programmer_path(@programmer) %> |
<%= link_to 'Back', programmers_path %>

app/views/user_ma_iler/welcome_email.text.erb
Welcome to example.com, <%= @user.name %>
===============================================
 
You have successfully signed up to example.com,
your username is: <%= @user.login %>.
 
To login to the site, just follow this link: <%= @url %>.
 
Thanks for joining and have a great day!